import esbuild from "esbuild";
import { readFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import process from "node:process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Edit src/ and run \`npm run build\`.
*/
`;

const prod = process.argv[2] === "production";

// Sucrase carries the source text of a React Hot Loader helper that contains `eval(code)`.
// That transform is never enabled here, and the text alone reads as dynamic code execution to
// the plugin review, so it is left out of the bundle.
const dropHotLoaderHelper = {
  name: "drop-hot-loader-helper",
  setup(build) {
    build.onLoad({ filter: /sucrase[\\/]dist[\\/]esm[\\/]transformers[\\/]RootTransformer\.js$/ }, async (args) => {
      const source = await readFile(args.path, "utf8");
      const helper = "{this[key] = eval(code);}";
      if (!source.includes(helper)) throw new Error("Sucrase changed; update dropHotLoaderHelper");
      return { contents: source.replace(helper, "{}"), loader: "js" };
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [dropHotLoaderHelper],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();
